/*
 * This script implements Bitcoin lock validation in ckb.
 *
 * How to verify Bitcoin lock?
 *
 * We know that the format of the Bitcoin address is
 * base58(version + ripemd160(sha256(pubkey)) + sha256(sha256(version +
 * ripemd160(sha256(pubkey))))[0..4])
 *
 * So by verifying the hash of ripemd160(sha256(pubkey)) and verifying the
 * ownership of the pubkey, you can achieve the purpose of verifying the
 * ownership of the private key.
 *
 * How to use this script?
 *
 * We need verify ripemd160(sha256(pubkey)), so transaction lock script like
 * this:
 *
 * ```
 * dependence_code_hash = "this script binary hash"
 * args = [ "ripemd160(sha256(pubkey))" ]
 * ```
 *
 * We need verify the ownership of the pubkey, so transaction witness is:
 *
 * witness = [signature, pubkey]
 *
 * if the signature if recoveravle, witness = [signature]
 *
 * Signature generated by your private key sign transaction hash
 */
#include "secp256k1_ripemd160_sha256_lock.h"

#include "ckb_syscalls.h"

/*
 * Arguments are listed in the following order:
 * 0. ripemd160(sha256(pubkey)) hash, used to
 * shield the real pubkey in lock script.
 *
 * Witness:
 * 0. signature, signature used to present ownership
 * 1. pubkey, real pubkey used to identify token owner
 *
 * or Witness:
 * 0. signature, signature used to present ownership
 */
int main() {
  int ret;
  uint64_t len = 0;

  /* Load args */
  unsigned char script[SCRIPT_SIZE];
  len = SCRIPT_SIZE;
  ret = ckb_load_script(script, &len, 0);
  if (ret != CKB_SUCCESS) {
    return ERROR_SYSCALL;
  }
  if (len > SCRIPT_SIZE) {
    return ERROR_SCRIPT_TOO_LONG;
  }
  mol_seg_t script_seg;
  script_seg.ptr = (uint8_t *)script;
  script_seg.size = len;

  if (MolReader_Script_verify(&script_seg, false) != MOL_OK) {
    return ERROR_ENCODING;
  }

  mol_seg_t args_seg = MolReader_Script_get_args(&script_seg);
  mol_seg_t args_bytes_seg = MolReader_Bytes_raw_bytes(&args_seg);
  if (args_bytes_seg.size != RIPEMD160_SIZE) {
    return ERROR_ARGUMENTS_LEN;
  }
  return verify_secp256k1_ripemd160_sha256_sighash_all(args_bytes_seg.ptr);
}
